[theme]

# Primary accent for interactive elements
primaryColor = '#FF0000'

# Background color for the main content area
backgroundColor = '#008000'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#228B22'

# Color used for almost all text
textColor = '#FFFF33'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "serif" 
