[theme]

# Primary accent for interactive elements
primaryColor = '#FFFF33'

# Background color for the main content area
backgroundColor = '#008000'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = 'Orange'

# Color used for almost all text
textColor = '#ff007f'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "monospace"
