[theme]

# Primary accent for interactive elements
primaryColor = 'Pink'

# Background color for the main content area
backgroundColor = '#00FFFF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = 'Orange'

# Color used for almost all text
textColor = '#89CFF0'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "monospace"
